### ISSUE TITLE
How to have a custom marker in a cluster example?

### ISSUE THREAD

**Issue by gajus** [visgl/react-map-gl#1044]
* https://uber.github.io/react-map-gl/examples/controls
* https://uber.github.io/react-map-gl/examples/clusters

These two examples demonstrate two features that I want:

* clustering
* custom marker

I understand how styling of layers work in the cluster example, though I don't understand how to add markers to a layer. In the cluster example, I wish to have a custom marker for `unclusteredPointLayer`.

**Comment by tbakerx** [comment]
Have a look at making it a type:'symbol'
https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#symbol

**Comment by yardiewizardie** [comment]
Hey @gajus , I had similar implementation as yours, I'm happy I figure out things, I would like to help you because there is little documentation about this.

Customization can be tricky, but you should focus on the mapbox docs, what worked for me are.
https://docs.mapbox.com/mapbox-gl-js/example/data-driven-circle-colors/ for custom color markers, for custom marker, they can be pretty limited, but symbol are working for me. My point is that to look for documentation in mapbox itself not the react-map-gl.... As for popup and other interaction with those, do use the onClick or getCursor function of MapGL, they are useful to interact with them. Hope this helps.

**Comment by webdeb** [comment]
@gajus Could you find a satisfying solution to render markers with clustering. me not yet.
Right now I am using the layers of unclustered / clustered points, which works but its limited in capabilities of the actual feature points (like applying styles programmatically etc.)

On the other hand I could use markers, but I could not find any clustering examples.

+1

**Comment by Pessimistress** [comment]
#507

**Comment by dberardo-com** [comment]
let me understand the scope of this issue ... is this about adding markers to a layer that then uses a cluster ?

something like  https://svelte-maplibre.vercel.app/examples/custom_marker_clusters ?
