### ISSUE TITLE
Marker moves when I zoom out the map

### ISSUE THREAD

**Issue by ahlag** [visgl/react-map-gl#1052]
I have created a marker while using the map tiles from maptiler. The marker moves away from the location when I zoom out the map. Is there a way to solve this issue? 

```
import React from "react";
import { useState } from 'react';
import ReactMapGL, {Marker} from 'react-map-gl';
import 'mapbox-gl/dist/mapbox-gl.css';
import Pin from './pin'

function FindHospitalPage() {
  const [viewport, setViewport] = useState({
    width: 1300,
    height: 600,
    latitude: 51.5,
    longitude: -0.09,
    zoom: 16
  });

  return (
    <ReactMapGL
      {...viewport}
      mapboxApiAccessToken={'not-needed'}
      mapStyle={"https://api.maptiler.com/maps/streets/style.json?key=RVqrAzdxmF8lTLoFpOJa"}
      onViewportChange={setViewport}
    >
      <Marker latitude={51.5} longitude={-0.09}>
        <Pin />
      </Marker>
    </ReactMapGL>
  );
}

export default FindHospitalPage;
```

**Comment by Pessimistress** [comment]
Do you see this problem with https://uber.github.io/react-map-gl/examples/controls ? If so, please include a screenshot/GIF.

Otherwise, provide a code sandbox link so that we can reproduce your issue.

**Comment by dfalling** [comment]
I ran into the same issue, but it was a problem on my end.  I looked through the examples and realized I needed to do a transform of my markers.

```javascript
const SIZE = 20;
const UNIT = "px";

<Marker style={{transform: `translate(${SIZE/2 + UNIT}, ${SIZE/2 + UNIT}` />
```

**Comment by aperkaz** [comment]
Looking into the docs and other issues @ahlag, setting the `offsetTop` and `offsetLeft` props in the Marker component fixed it for me.

Example:
Given you use an icon as a marker of size 20px (height) and 14px (width) [such as this one](https://material.io/resources/icons/?search=map&icon=room&style=baseline), in order to set the marker's bottom-center as the center for the latitude/longitute and avoid the zooming issues, you can:
```
<Marker offsetTop={-heigth}  offsetLeft={-width/2} ...otherProps />
     // offsetTop={-20}      offsetLeft={-7} 
```

**Comment by wkennedy8** [comment]
@aperkaz  thank you!!

**Comment by ahlag** [comment]
@aperkaz 
That worked for me! Thank you!

**Comment by dfalling** [comment]
> @ahlag , offsetTop width and height. Which width and height?

The width/height of your marker. aperkaz gave [a good example](https://github.com/visgl/react-map-gl/issues/1052#issuecomment-629120064) of this.

**Comment by wafisher** [comment]
Even on the [samples page](https://visgl.github.io/react-map-gl/examples/controls) the centering is off in Chrome. (@Pessimistress) The outer `<div>` is a few pixels larger than the `<svg>`, despite that being the only child. This throws the centering off. Very easy to see on our site because the markers are placed on other objects — harder to see on the linked sample page because there are no landmarks.

![Screenshot_8257](https://user-images.githubusercontent.com/3514570/160533092-263647ae-cdb4-439d-9363-ba8419d18674.jpg)

I can only get an SVG to center properly after setting `display: block` on the content, as is done on [this page](https://docs.mapbox.com/mapbox-gl-js/example/add-a-marker/). This works with this library, as well.

```
<Marker
  longitude={f.geometry.coordinates[0]}
  latitude={f.geometry.coordinates[1]}
  anchor={'center'}
  offset={[0, 0]}
  rotation={angle}
>
  <img
    <!-- This line is key -->
    style={{ display: 'block' }}
    src={droplet}
    height={size}
    alt={'Train marker'}
  />
</Marker>
```

**Comment by lqt123l** [comment]
In your index.js, add:
`import 'mapbox-gl/dist/mapbox-gl.css';`

**Comment by wafisher** [comment]
I had that and still no go but perhaps others can try and see if that works.

**Comment by Pessimistress** [comment]
@wafisher This issue was referring to a now outdated version of the library. If you think there is a bug with the current release, please create a new issue.

**Comment by liydaco** [comment]
> 

This worked for me, thanks.

**Comment by KudoExtase810** [comment]
life saver ! this works for the latest release
