### ISSUE TITLE
Marker Anchor

### ISSUE THREAD

**Issue by YousefED** [visgl/react-map-gl#1128]
mapbox gl has support for advanced properties on Markers like `anchor` (https://docs.mapbox.com/mapbox-gl-js/api/markers/#Marker). I know we can achieve a similar effect with offset in react-map-gl markers, but I'd prefer to use a similar API.

As react-map-gl is presented as a "wrapper" around mapbox gl it surprised me a little bit to see custom implementations for markers, popups, etc. Is there any reason in particular for this? Why use customized implementations instead of 1-1 React wrappers around the underlying API?

**Comment by Pessimistress** [comment]
mapbox-gl's API does not support using it as a fully controlled React component. In short, because React and Mapbox run separate render loops, we cannot guarantee that the map and any other component in the React tree gets updated at the same time, unless we block the map from handling user input.

You can see some relevant discussion in this thread:
- https://github.com/visgl/react-map-gl/issues/569
- https://github.com/visgl/react-map-gl/tree/master/docs#design-philosophy

We have discussed this with the Mapbox dev team but they were not convinced of the value in our use case.

As for markers, we can probably use React Portal to better reuse the native control code, but will run into the same issue when they are draggable.
