### ISSUE TITLE
FullscreenControl titel hard-coded

### ISSUE THREAD

**Issue by mazurp** [visgl/react-map-gl#1173]
In FullscreenControl component label/titel are hard-coded. Value is alweys 'Toggle fullscreen' so I'm not able to translate it on other languages.

**Comment by vfabioux** [comment]
Hi,

I have the same problem, I can't translate with that hard-coded title, especially since I'm using a data-title attribute for custom tooltips.
Is there any way to modify this component so that we can inject attributes into the button?
Even better: expose fullscreen and setFullscreen() so that we can make our own button easily.

Thanks

**Comment by Pessimistress** [comment]
We can add something similar to GeolocateControl's [label](http://visgl.github.io/react-map-gl/docs/api-reference/geolocate-control#label) prop.

It'd be greatly appreciated if you want to open a PR.

**Comment by Pessimistress** [comment]
Addressed in 5.2.9 (use `label` prop)
