### ISSUE TITLE
ReactMapGL mapboxApiAccessToken is not reactive

### ISSUE THREAD

**Issue by vfabioux** [visgl/react-map-gl#1395]
#### Description

Changing the value of mapboxApiAccessToken after component mount does not change the API token used for mapbox requests.
Changing this value live can be usefull to let designers with different accounts see how their own styles fit within an application.

#### Repro Steps

https://codesandbox.io/s/react-map-gl-api-token-bug-wfv47
Change the access token in the input box to your own, then set the style URL to one only you can access.
Nothing will happen, and you will see a 404 error code in dev tools, because it is still using the old access token.

#### Environment (please complete the following information):

- Library Version: react-map-gl 6.1.10
- Mapbox Version: mapbox-gl 2.1.1
- React Version: react 17.0.1
- Browser Version: Firefox 86.0
- OS: Kubuntu 20.04

**Comment by Pessimistress** [comment]
As the [documentation](https://visgl.github.io/react-map-gl/docs/api-reference/static-map#initialization) explains,  some props are only used when the map is first created. While we could have made `mapboxApiAccessToken` reactive, there is no Mapbox native API to update it, so we would have to destroy the Map instance and create a new one.

You can always force create a new Map instance by changing the `key` prop and therefore remounting the React component. There is no performance loss there since the underlying resources cannot be shared anyways.

**Comment by vfabioux** [comment]
I guess I read too fast, I did not see the text under the Initialization.

Thanks for the help!
