### ISSUE TITLE
[Bug] `<Map />` does not resize on programmatic

### ISSUE THREAD

**Issue by sumarlidason** [visgl/react-map-gl#1984]
### Description

`<Map />` component does not resize when container is resized programmatically. Interim fix for us was rolling back to `^6`.

https://codesandbox.io/s/deck-gl-react-map-gl-resize-issue-pomjrd

### Expected Behavior

canvas layers representing `<Map />` components to resize.

### Steps to Reproduce

See sandbox.

### Environment

- Framework version: `react-map-gl@7.0.19`
- Map library: `mapbox-gl@2.10.0`
- Browser: Chrome @ `105.0.5195.102 (Official Build) (arm64)`
- OS: `macOS 12.5.1`

**Comment by Pessimistress** [comment]
This is an intentional change. The underlying mapbox-gl only auto resizes when the browser window resizes. As of v7.0 react-map-gl always behaves the same as the base library, see https://visgl.github.io/react-map-gl/docs/upgrade-guide#upgrading-to-v70.

There are several API/libraries that you can use to track container resize, and then call `map.resize()`. react-map-gl v6 used to use [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver). You could also make a case to Mapbox GL JS that it should watch the container resize events.

**Comment by sumarlidason** [comment]
perfect, thank you!
