### ISSUE TITLE
[Bug] Circle layers have issues with globe projection

### ISSUE THREAD

**Issue by sh54** [visgl/react-map-gl#2136]
### Description

When the map projection is set to `globe` then I am experiencing two issues.

This occurs with a layer of `type=circle` with `paint.circle-radius = 20`.

Firstly when zooming in and out the layer pops in and out of visibility.

Secondly I am not able to find the feature via `queryRenderedFeatures` with a point argument. But without the point argument it gets found.

I guess this is probably an upstream issue but I have an example ready to go here with React.

### Visibility during zoom issue:

https://user-images.githubusercontent.com/906180/222965151-8c4afa38-82dd-479a-abf7-e7f5254185e0.mp4

### queryRenderedFeatures issue:

https://user-images.githubusercontent.com/906180/222965218-58eda007-2306-4c6d-a1ed-5cf04df38e40.mp4

### Expected Behavior

If I am in the default projection then neither of these issues happen. The circle remains visible. The circle is always findable with ~queryRenderedFeatures~.

### Steps to Reproduce

See [example](https://stackblitz.com/edit/react-ts-x1fxmh?file=MapView.tsx). Need to use your own mapbox api token.

### Environment

- Framework version: react-map-gl@7.0.21
- Map library: mapbox-gl@2.12.1
- Browser: Chrome
- OS: macOS

**Comment by dcyoung** [comment]
+1, we have encountered this issue and hoping for a fix or workaround

**Comment by IliyanID** [comment]
+ 1, we've also stumbled onto this issue. A fix would be appreciated

**Comment by jehie** [comment]
This issue seems to relate to the  this._renderTransform and the map.transform. For some reason the map instance transform has still globe set as the projection while the shadowTransform has the correct mercator projection (when zoomed in enough for the switch to happen).  So somehow the states are not synced properly, and when querying the features there is a mismatch between the point projection (globe) and the sourceCaches projection (mercator), while they should be both mercator at this zoom level.

Any ideas @Pessimistress how to solve this?

**Comment by jehie** [comment]
@Pessimistress, thanks for the fix. I was able to verify on our side that the fix solves the queryRenderedFeatures problem and also circles are not disappearing anymore.
