### ISSUE TITLE
[Bug] Github page not working

### ISSUE THREAD

**Issue by autimio** [visgl/react-map-gl#2440]
### Description

The page https://visgl.github.io/react-map-gl/ is not working.

### Steps to Reproduce

Go to the link https://visgl.github.io/react-map-gl/ and you'll notice that it won't load.

### Environment

- Browser: Browser-independent

**Comment by lattaai1** [comment]
Hello, I've fixed this issue!

This is what I've done:
I've identified that the issue might be related to the website's base URL and deployment configuration. To fix this, I'm updating the `docusaurus.config.js` file to ensure the correct base URL is set and the deployment settings are properly configured.

I also created pull request: https://github.com/visgl/react-map-gl/pull/2441


> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

**Comment by chrisgervang** [comment]
Might have been a temporary outage <img width="553" alt="Screenshot 2024-12-13 at 4 15 43 PM" src="https://github.com/user-attachments/assets/03cbde37-3973-4c22-bad1-1638fc43b91b" />
